### ISSUE TITLE
Fusion-bloom reporting "TypeError"  

### ISSUE THREAD

**Issue by Rohanbha** [bcgsc/pavfinder#15]
Hello,
I have run "fusion-bloom" script on multiple samples using the following command -

`fusion-bloom profile=fusion_profile_chickpea.txt left=SRR12081280/reads/SRR12081280_1_trim.fastq right=SRR12081280/reads/SRR12081280_2_trim.fastq readlen=125 outdir=SRR12081280/SRR12081280_FusionBloomOut name=chickfus`

I got results from some samples which are smaller in size (<2GB), but the script terminates for larger runs reporting an error -

"Traceback (most recent call last):
  File "/home/nipgr/software/pavfinder_env/bin/find_sv_transcriptome.py", line 259, in <module>
    main()
  File "/home/nipgr/software/pavfinder_env/bin/find_sv_transcriptome.py", line 226, in main
    only_fusions=args.only_fusions
  File "/home/nipgr/software/pavfinder_env/lib/python3.6/site-packages/pavfinder/transcriptome/sv_finder.py", line 297, in find_events
    events.extend(process_split_aligns([align1, align2], query_seq, genes))
  File "/home/nipgr/software/pavfinder_env/lib/python3.6/site-packages/pavfinder/transcriptome/sv_finder.py", line 158, in process_split_aligns
    self.update_adj(adj, aligns, query_seq, target_type, block_matches=block_matches)
  File "/home/nipgr/software/pavfinder_env/lib/python3.6/site-packages/pavfinder/transcriptome/sv_finder.py", line 723, in update_adj
    self.is_fusion(adj, (aligns[0].strand, aligns[1].strand), target_type)
  File "/home/nipgr/software/pavfinder_env/lib/python3.6/site-packages/pavfinder/transcriptome/sv_finder.py", line 1664, in is_fusion
    self.is_sense_fusion(adj, align_strands, target_type)
  File "/home/nipgr/software/pavfinder_env/lib/python3.6/site-packages/pavfinder/transcriptome/sv_finder.py", line 1719, in is_sense_fusion
    within_utrs = (adj.transcripts[0].within_utr(adj.genome_breaks[0]),
  File "/home/nipgr/software/pavfinder_env/lib/python3.6/site-packages/pavfinder/transcriptome/transcript.py", line 351, in within_utr
    if pos >= utr5[0] and pos <= utr5[1]:
TypeError: '>=' not supported between instances of 'NoneType' and 'int'"

Please help me out with this issue.

**Comment by readmanchiu** [comment]
Sorry @Rohanbha I glossed over this in my mailbox and apologized for the late reply.
I will fix this bug and update when it is done.

**Comment by readmanchiu** [comment]
Hi @Rohanbha,

Please try running again hopefully the bug is fixed.
